local callCounter = 0;

local function Ackermann( m, n )
	callCounter = callCounter + 1;

	if ( m == 0 ) then
		return n + 1;
	else if ( n == 0 ) then
		return Ackermann( m - 1, 1 );
	else
		return Ackermann( m - 1, Ackermann( m, n - 1 ) );
	end  
end

local function Fibonacci( n )
	callCounter = callCounter + 1;
	
	if ( n == 0 ) then return 0; end
	if ( n == 1 ) then return 1; end
	return Fibonacci( n - 1 ) + Fibonacci( n - 2 );
end

local function TailCall( n )
	if ( n == 0 ) then
		print( "done!" ); 
	else
		return TailCall( n - 1 );
	end
end

TailCall( 10000000 );